{
  "total_tests": 0,
  "total_passed": 0,
  "total_failed": 0,
  "total_skipped": 0,
  "total_execution_time": 54.23968965499989,
  "overall_coverage": 0.0,
  "quality_score": 0.0,
  "performance_benchmarks": {},
  "compliance_status": "FAIL",
  "suite_results": [
    {
      "suite_name": "core",
      "tests_run": 0,
      "tests_passed": 0,
      "tests_failed": 0,
      "tests_skipped": 0,
      "execution_time": 0.8652311199984979,
      "coverage_percentage": 10.0,
      "error_messages": [
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/security/access_control.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: line_bits (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/security/pii_protection.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/security/security_monitor.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/formatters.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/security_validator.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/unified_validators.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/validators.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/adapter.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/adapter_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/adapter_secure.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/adapter_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/audit_logger.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/batch_processor.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/cache.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/config.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/connection_pool.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/cost_tracker.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/example_usage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/fallback_manager.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/integrations.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/anthropic.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/anthropic_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/base.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/google.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/local.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/openai.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/openai_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/provider_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/rate_limiter.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/security.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/streaming.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/token_optimizer.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/validator.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/audit.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/engine.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/engine_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/engine_secure.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/engine_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/entropy.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/entropy_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/optimizer.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/patterns.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/patterns_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/rate_limiter.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/scorer.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/scorer_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/secure_cache.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/security.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/validators.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/analyzer.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/analyzer_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/base_dimension.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/config.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/dimensions.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/dimensions_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/exceptions.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/models.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/scoring.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/security.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/utils.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/validators.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/dimensions.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/dimensions_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/dimensions_secure.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/dimensions_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/example_usage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/models.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/review_engine.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/review_engine_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/review_engine_secure.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/review_engine_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/security_validator.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/utils.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/encryption.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/enhanced_pii_detector.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/fast_storage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/local_storage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/migrations.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/models.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/optimized_storage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/pii_detector.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/secure_storage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/utils.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/benchmark.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/benchmark_comparison.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/categories.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/exceptions.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/loader.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/models.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/parser.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/parser_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/parser_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/registry.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/registry_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/registry_secure.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/registry_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/secure_parser.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/template.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/template_sandbox.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/template_security.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/validator.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/pytest_cov/plugin.py:358: CovReportWarning: Failed to generate report: Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer",
        "  warnings.warn(CovReportWarning(message), stacklevel=1)"
      ]
    },
    {
      "suite_name": "validators",
      "tests_run": 0,
      "tests_passed": 0,
      "tests_failed": 0,
      "tests_skipped": 0,
      "execution_time": 0.7020377770004416,
      "coverage_percentage": 27.0,
      "error_messages": [
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/cli.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: line_bits (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/core/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/core/content_processor.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/core/engine.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/core/secure_template_loader.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/core/template_loader.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/core/template_registry_adapter.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/core/unified_engine.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/core/unified_template_loader.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/migrate_to_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/outputs/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/outputs/html.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/outputs/markdown.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/outputs/secure_html_output.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/outputs/unified_html_output.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/security/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/security/access_control.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/security/pii_protection.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/security/security_monitor.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/formatters.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/security_validator.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/unified_validators.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/validators.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/adapter.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/adapter_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/adapter_secure.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/adapter_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/audit_logger.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/batch_processor.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/cache.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/config.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/connection_pool.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/cost_tracker.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/example_usage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/fallback_manager.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/integrations.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/anthropic.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/anthropic_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/base.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/google.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/local.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/openai.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/openai_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/provider_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/rate_limiter.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/security.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/streaming.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/token_optimizer.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/validator.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/audit.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/engine.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/engine_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/engine_secure.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/engine_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/entropy.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/entropy_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/optimizer.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/patterns.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/patterns_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/rate_limiter.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/scorer.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/scorer_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/secure_cache.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/security.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/validators.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/analyzer.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/analyzer_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/base_dimension.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/config.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/dimensions.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/dimensions_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/exceptions.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/models.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/scoring.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/security.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/utils.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/validators.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/dimensions.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/dimensions_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/dimensions_secure.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/dimensions_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/example_usage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/models.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/review_engine.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/review_engine_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/review_engine_secure.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/review_engine_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/security_validator.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/utils.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/encryption.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/enhanced_pii_detector.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/fast_storage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/local_storage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/migrations.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/models.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/optimized_storage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/pii_detector.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/secure_storage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/utils.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/benchmark.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/benchmark_comparison.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/categories.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/exceptions.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/loader.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/models.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/parser.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/parser_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/parser_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/registry.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/registry_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/registry_secure.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/registry_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/secure_parser.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/template.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/template_sandbox.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/template_security.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/validator.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/pytest_cov/plugin.py:358: CovReportWarning: Failed to generate report: Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer",
        "  warnings.warn(CovReportWarning(message), stacklevel=1)"
      ]
    },
    {
      "suite_name": "generators",
      "tests_run": 0,
      "tests_passed": 0,
      "tests_failed": 0,
      "tests_skipped": 0,
      "execution_time": 2.1168390639995778,
      "coverage_percentage": 4.0,
      "error_messages": [
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:107: CoverageWarning: Couldn't parse Python file '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/security_validator.py' (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/cli.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: line_bits (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/core/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/core/content_processor.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/core/engine.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/core/secure_template_loader.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/core/template_loader.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/core/template_registry_adapter.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/core/unified_engine.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/core/unified_template_loader.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/migrate_to_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/outputs/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/outputs/html.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/outputs/markdown.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/outputs/secure_html_output.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/outputs/unified_html_output.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/security/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/security/access_control.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/security/pii_protection.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/security/security_monitor.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/formatters.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/security_validator.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/unified_validators.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/validators.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/adapter.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/adapter_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/adapter_secure.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/adapter_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/audit_logger.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/batch_processor.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/cache.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/config.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/connection_pool.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/cost_tracker.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/example_usage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/fallback_manager.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/integrations.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/anthropic.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/anthropic_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/base.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/google.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/local.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/openai.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/openai_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/provider_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/rate_limiter.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/security.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/streaming.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/token_optimizer.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/validator.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/audit.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/engine.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/engine_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/engine_secure.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/engine_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/entropy.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/entropy_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/optimizer.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/patterns.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/patterns_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/rate_limiter.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/scorer.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/scorer_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/secure_cache.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/security.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/validators.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/analyzer.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/analyzer_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/base_dimension.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/config.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/dimensions.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/dimensions_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/exceptions.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/models.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/scoring.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/security.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/utils.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/validators.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/dimensions.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/dimensions_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/dimensions_secure.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/dimensions_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/example_usage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/models.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/review_engine.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/review_engine_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/review_engine_secure.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/review_engine_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/security_validator.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/utils.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/encryption.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/enhanced_pii_detector.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/fast_storage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/local_storage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/migrations.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/models.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/optimized_storage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/pii_detector.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/secure_storage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/utils.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/benchmark.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/benchmark_comparison.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/categories.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/exceptions.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/loader.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/models.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/parser.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/parser_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/parser_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/registry.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/registry_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/registry_secure.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/registry_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/secure_parser.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/template.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/template_sandbox.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/template_security.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/validator.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/pytest_cov/plugin.py:358: CovReportWarning: Failed to generate report: Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: line_bits",
        "  warnings.warn(CovReportWarning(message), stacklevel=1)"
      ]
    },
    {
      "suite_name": "assertions",
      "tests_run": 0,
      "tests_passed": 0,
      "tests_failed": 0,
      "tests_skipped": 0,
      "execution_time": 0.9900434110004426,
      "coverage_percentage": 5.0,
      "error_messages": [
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:107: CoverageWarning: Couldn't parse Python file '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/security_validator.py' (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/integrations.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: line_bits (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/anthropic.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/anthropic_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/base.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/google.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/local.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/openai.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/openai_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/providers/provider_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/rate_limiter.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/security.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/streaming.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/token_optimizer.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/llm_adapter/validator.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/audit.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/engine.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/engine_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/engine_secure.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/engine_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/entropy.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/entropy_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/optimizer.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/patterns.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/patterns_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/rate_limiter.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/scorer.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/scorer_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/secure_cache.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/security.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/miair/validators.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/analyzer.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/analyzer_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/base_dimension.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/config.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/dimensions.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/dimensions_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/exceptions.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/models.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/scoring.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/security.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/utils.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/quality/validators.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/dimensions.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/dimensions_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/dimensions_secure.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/dimensions_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/example_usage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/models.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/review_engine.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/review_engine_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/review_engine_secure.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/review_engine_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/security_validator.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/review/utils.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/encryption.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/enhanced_pii_detector.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/fast_storage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/local_storage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/migrations.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/models.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/optimized_storage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/pii_detector.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/secure_storage.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/storage/utils.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/__init__.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/benchmark.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/benchmark_comparison.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/categories.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/exceptions.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/loader.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/models.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/parser.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/parser_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/parser_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/registry.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/registry_optimized.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/registry_secure.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/registry_unified.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/secure_parser.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/template.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/template_sandbox.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/template_security.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:113: CoverageWarning: Couldn't parse '/workspaces/DocDevAI-v3.0.0/devdocai/templates/validator.py': Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")",
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/pytest_cov/plugin.py:358: CovReportWarning: Failed to generate report: Couldn't use data file '/workspaces/DocDevAI-v3.0.0/.coverage': no such table: tracer",
        "  warnings.warn(CovReportWarning(message), stacklevel=1)"
      ]
    },
    {
      "suite_name": "spdx_validators",
      "tests_run": 0,
      "tests_passed": 0,
      "tests_failed": 0,
      "tests_skipped": 0,
      "execution_time": 9.884316650000983,
      "coverage_percentage": 3.0,
      "error_messages": [
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:107: CoverageWarning: Couldn't parse Python file '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/security_validator.py' (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")"
      ]
    },
    {
      "suite_name": "cyclonedx_validators",
      "tests_run": 0,
      "tests_passed": 0,
      "tests_failed": 0,
      "tests_skipped": 0,
      "execution_time": 9.827325621001364,
      "coverage_percentage": 1.0,
      "error_messages": [
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:107: CoverageWarning: Couldn't parse Python file '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/security_validator.py' (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")"
      ]
    },
    {
      "suite_name": "signatures",
      "tests_run": 0,
      "tests_passed": 0,
      "tests_failed": 0,
      "tests_skipped": 0,
      "execution_time": 9.910969874001239,
      "coverage_percentage": 1.0,
      "error_messages": [
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:107: CoverageWarning: Couldn't parse Python file '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/security_validator.py' (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")"
      ]
    },
    {
      "suite_name": "performance",
      "tests_run": 0,
      "tests_passed": 0,
      "tests_failed": 0,
      "tests_skipped": 0,
      "execution_time": 9.576208070000575,
      "coverage_percentage": 1.0,
      "error_messages": [
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:107: CoverageWarning: Couldn't parse Python file '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/security_validator.py' (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")"
      ]
    },
    {
      "suite_name": "integration",
      "tests_run": 0,
      "tests_passed": 0,
      "tests_failed": 0,
      "tests_skipped": 0,
      "execution_time": 10.366050978998828,
      "coverage_percentage": 2.0,
      "error_messages": [
        "/usr/local/python/3.11.13/lib/python3.11/site-packages/coverage/report_core.py:107: CoverageWarning: Couldn't parse Python file '/workspaces/DocDevAI-v3.0.0/devdocai/generator/utils/security_validator.py' (couldnt-parse)",
        "  coverage._warn(msg, slug=\"couldnt-parse\")"
      ]
    }
  ]
}